// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Form(Props) {
  var onSubmit = Props.onSubmit;
  var children = Props.children;
  return React.createElement("form", {
              onSubmit: (function (e) {
                  e.preventDefault();
                  return Curry._1(onSubmit, /* () */0);
                })
            }, children);
}

var make = Form;

exports.make = make;
/* react Not a pure module */
