// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Field(Props) {
  var name = Props.name;
  var onChange = Props.onChange;
  var value = Props.value;
  return React.createElement("div", undefined, React.createElement("label", {
                  htmlFor: name
                }, name), React.createElement("input", {
                  name: name,
                  value: value,
                  onChange: onChange
                }));
}

var make = Field;

exports.make = make;
/* react Not a pure module */
