// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Webapi__Dom__Element = require("bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Element.js");
var Webapi__Dom__Document = require("bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Document.js");

function convert(param) {
  if (param) {
    return "auto";
  } else {
    return "hidden";
  }
}

function setScrollLock(value) {
  var partial_arg = "overflow:" + (
    value ? "auto" : "hidden"
  );
  return Belt_Option.mapWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(Webapi__Dom__Document.asHtmlDocument(document), (function (prim) {
                        return Caml_option.nullable_to_opt(prim.body);
                      })), Webapi__Dom__Element.asHtmlElement), /* () */0, (function (param) {
                param.setAttribute("style", partial_arg);
                return /* () */0;
              }));
}

exports.convert = convert;
exports.setScrollLock = setScrollLock;
/* Webapi__Dom__Element Not a pure module */
