// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function App$Modal(Props) {
  var isOpen = Props.isOpen;
  if (isOpen) {
    return React.createElement("div", undefined, "this is the modal");
  } else {
    return null;
  }
}

var Modal = /* module */[/* make */App$Modal];

function App(Props) {
  var match = React.useState((function () {
          return false;
        }));
  var setOpen = match[1];
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (_e) {
                      return Curry._1(setOpen, (function (prevState) {
                                    return !prevState;
                                  }));
                    })
                }, "open the modal"), React.createElement(App$Modal, {
                  isOpen: match[0]
                }));
}

var make = App;

exports.Modal = Modal;
exports.make = make;
/* react Not a pure module */
