// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Modal$ReactHooksTemplate = require("./components/Modal/Modal.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Modal$ReactHooksTemplate.make, { }), "root");

/*  Not a pure module */
